### ISSUE TITLE
6502 Random Logic (Logisim)

### ISSUE THREAD

**Issue by reklrekl** [emu-russia/breaks#117]
In the Logisim circuit of the Decoder and Random logic (Docs/6502/6502_logisim/RANDOM.circ):

Pin 102 is labeled JMP/4 and is connected to #DL/DB.

But according to the transistor drawings and Visual6502 Pin 101 is JMP/4 and connected to #DL/DB.
Is this an error in the Logisim circuit or are the Pins swapped in the decoder? (I've checked and it doesen't look like they are).

Which variant is correct? Thanks!

Also: sorry, I don't speak russian, I hope english is fine

**Comment by ogamespec** [comment]
I checked, there is indeed an error in the Logisim circuit. JMP/4 should be D101.
Thank you!
